#!/usr/bin/env bash
swayidle -w timeout 600 ~/.config/river/scripts/lockscreen timeout 600 'riverctl spawn dpms off' resume 'riverctl spawn dpms on' before-sleep ~/.config/river/scripts/lockscreen
exit
